tag = "savage_summit-summit_systems"
writes = [
    "savage_summit-BeastStats",
    "savage_summit-BeastDetails",
    "savage_summit-ConsumableDetails",
    "savage_summit-Summit",
    "savage_summit-SummitHistory",
]
