kind = "DojoModel"
class_hash = "0x3100b8dc3d3e3bb53ebd75eacc0dbc2cd640a4d3747ef829df5009af8f5259b"
original_class_hash = "0x3100b8dc3d3e3bb53ebd75eacc0dbc2cd640a4d3747ef829df5009af8f5259b"
abi = "manifests/dev/base/abis/models/savage_summit-SummitHistory-b317749a.json"
tag = "savage_summit-SummitHistory"
qualified_path = "savage_summit::models::summit::summit_history"
manifest_name = "savage_summit-SummitHistory-b317749a"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "lost_at"
type = "u64"
key = true

[[members]]
name = "taken_at"
type = "u64"
key = false

[[members]]
name = "rewards"
type = "u64"
key = false
