kind = "DojoModel"
class_hash = "0x102b3e2faf9fb1bf7ca06a5d670b863a4f98d56f49e19dca709cf2ff2ac4047"
original_class_hash = "0x102b3e2faf9fb1bf7ca06a5d670b863a4f98d56f49e19dca709cf2ff2ac4047"
abi = "manifests/dev/base/abis/models/savage_summit-Beast-2a5259df.json"
tag = "savage_summit-Beast"
manifest_name = "savage_summit-Beast-2a5259df"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "health"
type = "u16"
key = false

[[members]]
name = "dead_at"
type = "u64"
key = false

[[members]]
name = "consumables"
type = "Array<Consumable>"
key = false
