kind = "DojoModel"
class_hash = "0x6a697901f6a765f52fab282a55da8699686c0643bd4200fd9b13ebe7495f30"
original_class_hash = "0x6a697901f6a765f52fab282a55da8699686c0643bd4200fd9b13ebe7495f30"
abi = "manifests/dev/base/abis/models/savage_summit-ConsumableDetails-77c83828.json"
tag = "savage_summit-ConsumableDetails"
manifest_name = "savage_summit-ConsumableDetails-77c83828"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "_type"
type = "ConsumableType"
key = false
