kind = "DojoModel"
class_hash = "0x63591ef2e5285e67bc77b77c1fa155d2482c28332ccdee82474428ff50b03dd"
original_class_hash = "0x63591ef2e5285e67bc77b77c1fa155d2482c28332ccdee82474428ff50b03dd"
abi = "manifests/dev/base/abis/models/savage_summit-Summit-184adf2d.json"
tag = "savage_summit-Summit"
manifest_name = "savage_summit-Summit-184adf2d"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "beast_id"
type = "u32"
key = false
