kind = "DojoModel"
class_hash = "0x441a4aa61e899ecbba9408790e44212ac8dcb080f8a678ce30761cba037b6c"
original_class_hash = "0x441a4aa61e899ecbba9408790e44212ac8dcb080f8a678ce30761cba037b6c"
abi = "manifests/dev/base/abis/models/savage_summit-Consumable-6d35ac82.json"
tag = "savage_summit-Consumable"
manifest_name = "savage_summit-Consumable-6d35ac82"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "amount"
type = "u8"
key = false
