kind = "DojoModel"
class_hash = "0x4218a61f3eebf6eba0091627c52d95f1e9ab7c4535d0a42b6f5ca58cc1afa1f"
original_class_hash = "0x4218a61f3eebf6eba0091627c52d95f1e9ab7c4535d0a42b6f5ca58cc1afa1f"
abi = "manifests/dev/base/abis/models/savage_summit-Summit-184adf2d.json"
tag = "savage_summit-Summit"
qualified_path = "savage_summit::models::summit::summit"
manifest_name = "savage_summit-Summit-184adf2d"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "beast_id"
type = "u32"
key = false
