[world]
seed = "savage_summit"
name = "savage_summit"
description = "Take the hill"
website = "https://github.com/provablegames"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/provablegames"

[namespace]
default = "savage_summit"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
# world_address = "0x8d8e73b20e205f98347501a072701e3b7b55c6048ff78562c025aa8a5571a0"
