[world]
seed = "summit"
name = "Summit"
description = "Crown the Beast"
website = "https://github.com/provablegames"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/provablegames"

[namespace]
default = "savage_summit"

[env]
# world_address = "0x7d27b3fb263c94dd5c8fc142a9a1a574b77799946cea9521a8e98cc0ba2a076"
