kind = "DojoContract"
class_hash = "0x3e63e8d663a4406c7c8c7f069b5c1cb778b500135a5823ef615f304f1f903c6"
original_class_hash = "0x3e63e8d663a4406c7c8c7f069b5c1cb778b500135a5823ef615f304f1f903c6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/savage_summit-summit_systems-237ab367.json"
reads = []
writes = []
init_calldata = []
tag = "savage_summit-summit_systems"
systems = [
    "attack",
    "add_beast_details",
    "add_beast_stats",
]
manifest_name = "savage_summit-summit_systems-237ab367"
