kind = "DojoContract"
class_hash = "0x6be1667c49d9cb0a161fb342fa05a3b679653b217f34ae3971708a4371b7747"
original_class_hash = "0x6be1667c49d9cb0a161fb342fa05a3b679653b217f34ae3971708a4371b7747"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/savage_summit-game_systems-1a8a6dc8.json"
reads = []
writes = []
init_calldata = []
tag = "savage_summit-game_systems"
systems = ["attack"]
manifest_name = "savage_summit-game_systems-1a8a6dc8"
